# Generated by Django 4.2.19 on 2025-03-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
