# Generated by Django 5.1.4 on 2025-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
