# Generated by Django 5.1.6 on 2025-03-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.IntegerField(help_text='Delivery time in days')),
                ('proposal_text', models.TextField(help_text="Your detailed proposal explaining how you'll handle the project")),
                ('proposal_highlights', models.TextField(blank=True, help_text='Key points of your proposal (optional)', null=True)),
                ('technical_approach', models.TextField(blank=True, help_text='Your technical approach to the project (optional)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_breakdown', models.TextField(blank=True, help_text='Breakdown of project milestones and deliverables', null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='bid_attachments/')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='freelancer.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='freelancer.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
