# Generated by Django 4.2.19 on 2025-03-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_client'),
        ('freelancer', '0003_freelancer_about_me'),
    ]

    operations = [
    ]
