# Generated by Django 5.1.6 on 2025-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_freelancer_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=255)),
                ('businessEmail', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField(max_length=15)),
            ],
        ),
    ]
