# Generated by Django 4.2.19 on 2025-03-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_merge_0002_client_0003_freelancer_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='about_me',
        ),
    ]
